baseurl = "https://mekops.com/"  # Include trailing slash
copyright = "© CC-BY-4.0 by MekOps"
pagination.pagerSize = 10
theme = "hugo-clarity"
DefaultContentLanguage = "en"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params.giscus]
  enable = true
  repo = "mekops-labs/mekops.com"
  repoId = "R_kgDORAgYpw"
  category = "Comments"
  categoryId = "DIC_kwDORAgYp84C1Yd9"
  mapping = "pathname"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "en"
  loading = "lazy"
