baseurl = "https://mekops.com/"  # Include trailing slash
copyright = "© CC-BY-4.0 by MekOps"
pagination.pagerSize = 10
theme = "hugo-clarity"
DefaultContentLanguage = "en"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"
