[[main]]
  name = "/home"
  url = ""
  weight = -110

[[main]]
  name = "/projects"
  url = "projects/"
  weight = -109


# Submenus are done this way: parent -> identifier

[[main]]
  name = "/about"
  url = "about/"
  weight = -108

[[main]]
  name = "/old-stuff"
  url = "https://mek-x.github.io"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/mekops-labs/#"
[[social]]
  name = "gitlab"
  weight = 2
  url = "https://gitlab.com/mek_x/#"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/kamil-wcislo/#"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"
